CREATE TABLE [dbo].[Site]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [DirectionID] INT NOT NULL, 
    [Site] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT [FK_Site_ToDirection] FOREIGN KEY ([DirectionID]) REFERENCES Direction(Id) On DELETE CASCADE
)
